### ISSUE TITLE
Getting EBADF 

### ISSUE THREAD

**Issue by dickhardt** [TooTallNate/node-upnp-client#2]
34: this.server.addMembership(BROADCAST_ADDR); is throwing an EBADF exception

**Comment by SamDecrock** [comment]
I'm getting:

``` javascript
Error: addMembership EBADF
    at new errnoException (dgram.js:352:11)
    at Socket.addMembership (dgram.js:278:11)
    at new ControlPoint (/Users/sam/projects/dlnaremote/node-upnp-client/lib/upnp.js:34:15)
    at Object.<anonymous> (/Users/sam/projects/dlnaremote/node-upnp-client/test.js:4:20)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by SamDecrock** [comment]
Ok, found it

You have to put this

``` javascript
this.server.addMembership(BROADCAST_ADDR);
```

behind this

``` javascript
this.server.bind(SSDP_PORT);
```

as stated here: https://github.com/joyent/node/issues/3254#issuecomment-5651416

**Comment by neeagl** [comment]
It didn't work for me.

```
function ControlPoint() { 
  events.EventEmitter.call(this);
  this.server = dgram.createSocket('udp4');
  var self = this;
  this.server.on('message', function(msg, rinfo) {self.onRequestMessage(msg, rinfo);});
  this._initParsers();
  this.server.bind(SSDP_PORT);
  this.server.addMembership(BROADCAST_ADDR);
}
```

**Comment by vijaybritto** [comment]
[look here for solution](https://github.com/joyent/node/issues/4944)
