### ISSUE TITLE
property 'readable' undefined in the http parser

### ISSUE THREAD

**Issue by SamDecrock** [TooTallNate/node-upnp-client#3]
Your using the undocumented http parser and now it gives me the following error:

``` javascript
http.js:140
    if (parser.socket.readable) {
                     ^
TypeError: Cannot read property 'readable' of undefined
    at HTTPParser.onMessageComplete (http.js:140:22)
    at ControlPoint.onRequestMessage (/Users/sam/projects/dlnaremote/node-upnp-client/lib/upnp.js:47:32)
    at Socket.<anonymous> (/Users/sam/projects/dlnaremote/node-upnp-client/lib/upnp.js:35:56)
    at Socket.emit (events.js:70:17)
    at UDP.onMessage [as onmessage] (dgram.js:345:10)
```

**Comment by SamDecrock** [comment]
Ok, the soluction is to add an empty socket object to the parser...

In 

``` javascript
ControlPoint.prototype._initParsers = function(){ ... }
```

add:

``` javascript
self.requestParser.socket = { };
```
